# Generated by Django 6.1.2 on 2026-10-07 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9][0-9 ()\\-]{4,18}$",
                        "Телефон может содержать только цифры, пробелы, скобки, дефис и + в начале.",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
