# Generated by Django 6.1.2 on 2026-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Категория"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="color",
            field=models.CharField(
                choices=[
                    ("#FEFAF4", "Бумага"),
                    ("#FFF9C4", "Жёлтый"),
                    ("#E3F2FD", "Голубой"),
                    ("#FCE4EC", "Розовый"),
                ],
                default="#FEFAF4",
                max_length=7,
                verbose_name="Цвет",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="Важное"),
        ),
    ]
